/* Pins */
#define PIN_GPS_RX 4
#define PIN_GPS_TX 5
#define PIN_DHT11 6
#define PIN_PROXY_SENSOR 7
#define PIN_AIR_QUALITY A0
#define PIN_WIND_SENSOR A1

/* Communication */
#define RECEIVE_MESSAGE_DELIMITER '\n'
#define SEND_MESSAGE_DELIMITER '\r'
#define _SS_MAX_RX_BUFF 512
#define BT_BAUD_RATE 9600
#define GPS_BAUD_RATE 9600

/* States */
#define STATE_START "RTWL:START\r"
#define STATE_ERROR 'E'
#define STATE_GPS_NOT_WORKING 'G'
#define STATE_GPS_INVALID_DATA 'g'
#define STATE_TEMP_HUM_SENSOR_NOT_WORKING 'D'
#define STATE_TEMP_INVALID_DATA 't'
#define STATE_HUM_INVALID_DATA 'h'
#define STATE_PROXY_SENSOR_NOT_WORKING 'P'
#define STATE_WIND_SENSOR_NOT_WORKING 'W'
#define STATE_WIND_SENSOR_INVALID_DATA 'w'
#define STATE_WEATHER_CODE_INVALID 'c'
#define STATE_AIR_SENSOR_NOT_WORKING 'A'
#define STATE_AIR_SENSOR_INVALID_DATA 'a'
#define STATE_GET_GPS_COORDINATES_ENABLED 'L'
#define STATE_GET_GPS_COORDINATES_DISABLED 'l'
  
/*
  COMMANDS
  All command must be UPPERCASE letters
  Space character (" " or ascii:32) is ignored 
  Don't write bellow commands with spaces)
*/
#define UNKNOWN_COMMAND "u"
#define COMMAND_RESET_INTEGER "-1"
#define COMMAND_RESET_SHORT "RS"
#define COMMAND_RESET_LONG "RESET"
#define COMMAND_GET_RESPONSE_INTEGER "0"
#define COMMAND_GET_RESPONSE_SHORT "GR"
#define COMMAND_GET_RESPONSE_LONG "PING"
#define COMMAND_GET_DATA_INTEGER "1"
#define COMMAND_GET_DATA_SHORT "GD"
#define COMMAND_GET_DATA_LONG "GETDATA"
#define COMMAND_PROXIMITY_SENSOR_DEFECTION_INTEGER "2"
#define COMMAND_PROXIMITY_SENSOR_DEFECTION_SHORT "PD"
#define COMMAND_PROXIMITY_SENSOR_DEFECTION_LONG "PROXYFAIL"
#define COMMAND_GET_GPS_COORDINATES_INTEGER "3"
#define COMMAND_GET_GPS_COORDINATES_SHORT "GC"
#define COMMAND_GET_GPS_COORDINATES_LONG "GETCOORDINATES"
#define COMMAND_DISABLE_GET_GPS_COORDINATES_INTEGER "4"
#define COMMAND_DISABLE_GET_GPS_COORDINATES_SHORT "DGC"
#define COMMAND_DISABLE_GET_GPS_COORDINATES_LONG "DISABLEGETCOORDINATES"

/* Limits */
#define LIMIT_MIN_WEATHER_CODE 100
#define LIMIT_MAX_WEATHER_CODE 499
#define LIMIT_MIN_TEMPERATURE -50
#define LIMIT_MAX_TEMPERATURE 50
#define LIMIT_MIN_HUMIDITY 0
#define LIMIT_MAX_HUMIDITY 100
#define LIMIT_MIN_AIR 3
#define LIMIT_MAX_AIR 100
#define LIMIT_MIN_WIND 50
#define LIMIT_MAX_WIND 1024

/* Timing */
#define ONE_SECOND 1000
#define MAXIMUM_TIME_READINGS_STARTUP 3000
#define READING_DELAY 5000 // > 1100

/* Counters */
#define NUMBER_OF_READINGS_STARTUP 5
/* If the sensors or modules failed at least X times -> not working */
#define FAILURES_GPS 15
#define FAILURES_AIR_QUALITY 2

/* Memory size */
#define SIZE_RECEIVING_STRING 16
#define SIZE_MESSAGE_TO_SEND 40
#define SIZE_COORDINATES 20

/* The serial communication will be made only with the Bluetooth module
    This is a just a nickname to better understand the code */
#define Bluetooth Serial
